version: '3.8'

services:
  mysql:
    image: mysql:8.0.32
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: pagesale
      MYSQL_USER: gymmtp
      MYSQL_PASSWORD: gymmtp
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
